Diplomka/Controllers/DepotController.cs
using Diplomka.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Diplomka.Controllers
{
    public class DepotController : Controller
    {
        MyBaseContext db;

        public DepotController(MyBaseContext context)
        {
            db = context;
        }
        public ActionResult Depots()
        {
            IQueryable<Depot> depots = db.Depots;
            return View(depots.ToList());
        }

        //=======================================================

        public ActionResult Cars()
        {
            IQueryable<Car> cars = db.Cars.Include(с => с.Depot);
            return View(cars.ToList());
        }

        //=======================================================

        public ActionResult Drivers()
        {
            IQueryable<Driver> drivers = db.Drivers.Include(d => d.Car);
            return View(drivers.ToList());
        }

        //=======================================================

        public IActionResult CreateDepot()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDepot(Depot depot)
        {
            db.Depots.Add(depot);
            await db.SaveChangesAsync();
            return RedirectToAction("AddDepotsWays");
        }

        public async Task<IActionResult> AddDepotsWays()
        {
            Random random = new Random();
            Depot depot = new Depot();
            depot = db.Depots.OrderByDescending(p => p.DepotID).First(p => !String.IsNullOrEmpty(p.DepotID.ToString()));
            foreach (Warehouse i in db.Warehouses)
            {
                DistanceReference distanceReference = new DistanceReference();
                distanceReference.ID_FirstPoint = depot.DepotID;
                distanceReference.NameFirstPoint = depot.Name;
                distanceReference.TypeFirstPoint = "Автобаза";
                distanceReference.ID_SecondPoint = i.WarehouseID;
                distanceReference.NameSecondPoint = i.Name;
                distanceReference.TypeSecondPoint = "Склад";
                distanceReference.Distance = random.Next(15, 200);
                db.DistanceReferences.Add(distanceReference);
            }
            foreach (Factory i in db.Factories)
            {
                DistanceReference distanceReference = new DistanceReference();
                distanceReference.ID_FirstPoint = i.FactoryID;
                distanceReference.NameFirstPoint = i.Name;
                distanceReference.TypeFirstPoint = "Завод";
                distanceReference.ID_SecondPoint = depot.DepotID;
                distanceReference.NameSecondPoint = depot.Name;
                distanceReference.TypeSecondPoint = "Автобаза";
                distanceReference.Distance = random.Next(15, 200);
                db.DistanceReferences.Add(distanceReference);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Depots");
        }
        //=======================================================

        public IActionResult CreateCar()
        {
            ViewBag.Depot = new SelectList(db.Depots.ToList(), "DepotID", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCar(Car car)
        {
            car.Status = "Свободен";
            db.Cars.Add(car);
            await db.SaveChangesAsync();
            return RedirectToAction("Cars");
        }

        //=======================================================

        public IActionResult CreateDriver()
        {
            ViewBag.Car = new SelectList(db.Cars.ToList(), "CarID", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDriver(Driver driver)
        {
            db.Drivers.Add(driver);
            await db.SaveChangesAsync();
            return RedirectToAction("Drivers");
        }

        //=======================================================

        public ActionResult BackToDepots()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("Depots");
        }

        //=======================================================

        public ActionResult BackToCars()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("Cars");
        }

        //=======================================================

        public ActionResult BackToDrivers()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("Drivers");
        }

        //=======================================================

        public async Task<IActionResult> EditDepot(int? id)
        {
            if (id != null)
            {
                Depot depot = await db.Depots.FirstOrDefaultAsync(d => d.DepotID == id);
                if (depot != null)
                    return View(depot);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditDepot(Depot depot)
        {
            db.Depots.Update(depot);
            await db.SaveChangesAsync();
            return RedirectToAction("Depots");
        }

        //=======================================================

        public async Task<IActionResult> EditCar(int? id)
        {
            ViewBag.Depot = new SelectList(db.Depots.ToList(), "DepotID", "Name");

            if (id != null)
            {
                Car car = await db.Cars.FirstOrDefaultAsync(c => c.CarID == id);
                if (car != null)
                    return View(car);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditCar(Car car)
        {
            car.Status = "Свободен";
            db.Cars.Update(car);
            await db.SaveChangesAsync();
            return RedirectToAction("Cars");
        }

        //=======================================================

        public async Task<IActionResult> EditDriver(int? id)
        {
            ViewBag.Car = new SelectList(db.Cars.ToList(), "CarID", "Name");

            if (id != null)
            {
                Driver driver = await db.Drivers.FirstOrDefaultAsync(d => d.DriverID == id);
                if (driver != null)
                    return View(driver);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditDriver(Driver driver)
        {
            db.Drivers.Update(driver);
            await db.SaveChangesAsync();
            return RedirectToAction("Drivers");
        }

        //=======================================================

        [HttpGet]
        [ActionName("DeleteDepot")]
        public async Task<IActionResult> ConfirmDeleteDepot(int? id)
        {
            if (id != null)
            {
                Depot depot = await db.Depots.FirstOrDefaultAsync(d => d.DepotID == id);
                if (depot != null)
                    return View(depot);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDepot(int? id)
        {
            if (id != null)
            {
                Depot depot = await db.Depots.FirstOrDefaultAsync(d => d.DepotID == id);
                if (depot != null)
                {
                    db.Depots.Remove(depot);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Depots");
                }
            }
            return NotFound();
        }

        //=======================================================

        [HttpGet]
        [ActionName("DeleteCar")]
        public async Task<IActionResult> ConfirmDeleteCar(int? id)
        {
            if (id != null)
            {
                Car car = await db.Cars.FirstOrDefaultAsync(c => c.CarID == id);
                if (car != null)
                    return View(car);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCar(int? id)
        {
            if (id != null)
            {
                Car car = await db.Cars.FirstOrDefaultAsync(c => c.CarID == id);
                if (car != null)
                {
                    db.Cars.Remove(car);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Cars");
                }
            }
            return NotFound();
        }

        //=======================================================

        [HttpGet]
        [ActionName("DeleteDriver")]
        public async Task<IActionResult> ConfirmDeleteDriver(int? id)
        {
            if (id != null)
            {
                Driver driver = await db.Drivers.FirstOrDefaultAsync(d => d.DriverID == id);
                if (driver != null)
                    return View(driver);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDriver(int? id)
        {
            if (id != null)
            {
                Driver driver = await db.Drivers.FirstOrDefaultAsync(d => d.DriverID == id);
                if (driver != null)
                {
                    db.Drivers.Remove(driver);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Drivers");
                }
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

Diplomka/Controllers/OrderController.cs
using Diplomka.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Diplomka.Controllers
{
    public class OrderController : Controller
    {
        MyBaseContext db;

        public OrderController(MyBaseContext context)
        {
            db = context;
        }

        [Authorize(Roles = "Администратор, Планировщик, Заказчик")]
        public ActionResult Orders(string status)
        {
            IQueryable<Order> orders = db.Orders.Include(o => o.Factory)
                                                 .Include(o => o.Grain);
            return View(orders.ToList());
        }

        //=======================================================
        [Authorize(Roles = "Заказчик")]
        public IActionResult Create()
        {
            ViewBag.Factory = new SelectList(db.Factories.ToList(), "FactoryID", "Name");
            ViewBag.Grain = new SelectList(db.Grains.ToList(), "GrainID", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Заказчик")]
        public async Task<IActionResult> Create(Order order)
        {
            Grain grain = await db.Grains.FirstOrDefaultAsync(g => g.GrainID == order.GrainID);
            order.Status = "Активен";
            order.Price = order.Volume * grain.Price;
            
            db.Orders.Add(order);
            await db.SaveChangesAsync();
            return RedirectToAction("Orders");
        }


        //=======================================================
        public ActionResult BackToHome()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("Orders");
        }

        //=======================================================

        [Authorize(Roles = "Заказчик")]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Factory = new SelectList(db.Factories.ToList(), "FactoryID", "Name");
            ViewBag.Grain = new SelectList(db.Grains.ToList(), "GrainID", "Name");

            if (id != null)
            {
                Order orders = await db.Orders.FirstOrDefaultAsync(p => p.OrderID == id);
                if (orders != null)
                    return View(orders);
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Заказчик")]
        public async Task<IActionResult> Edit(Order orders)
        {
            Grain grain = await db.Grains.FirstOrDefaultAsync(g => g.GrainID == orders.GrainID);
            orders.Status = "Активен";
            orders.Price = orders.Volume * grain.Price;
            db.Orders.Update(orders);
            await db.SaveChangesAsync();
            return RedirectToAction("Orders");
        }

        //=======================================================

        [HttpGet]
        [ActionName("Delete")]
        [Authorize(Roles = "Заказчик")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.OrderID == id);
                if (order != null)
                    return View(order);
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Заказчик")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.OrderID == id);
                if (order != null)
                {
                    db.Orders.Remove(order);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Orders");
                }
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Diplomka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]-веб-</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Личный кабинет</a>       
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>      
	               
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(RoleEnum.Администратор.ToString()))
                        {                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Users">Пользователи</a>
                        </li>                       
                        }
                        @if (User.IsInRole(RoleEnum.Администратор.ToString()) || User.IsInRole(RoleEnum.Планировщик.ToString()))
                        {                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Applications">Заявки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Orders">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Factory" asp-action="Factories">Заводы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Warehouses">Склады</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Depot" asp-action="Depots">Автобазы</a>
                        </li>
                        }

                        @if (User.IsInRole(RoleEnum.Заказчик.ToString()))
                        {                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Orders">Заказы</a>
                        </li>                                              
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Дипломная работа - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> 