Diplomka/Models/Factory.cs
using System.Collections.Generic;

namespace Diplomka.Models
{
    public class Factory  //заводы
    {
        public int FactoryID { get; set; }
        public int Identity { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }              

    }
}

Diplomka/Controllers/FactoryController.cs
using Diplomka.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Diplomka.Controllers
{
    public class FactoryController : Controller
    {
        MyBaseContext db;

        public FactoryController(MyBaseContext context)
        {
            db = context;
        }
        public ActionResult Factories()
        {
            IQueryable<Factory> factories = db.Factories;
            return View(factories.ToList());
        }

        //=======================================================

        public IActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Factory factory)
        {           
            db.Factories.Add(factory);
            await db.SaveChangesAsync();
            return RedirectToAction("AddFactoriesWays");
        }

        public async Task<IActionResult> AddFactoriesWays()
        {
            Factory factories = new Factory();
            factories = db.Factories.OrderByDescending(p => p.FactoryID).First(p => !String.IsNullOrEmpty(p.FactoryID.ToString()));
            Random random = new Random();
            foreach (Warehouse i in db.Warehouses)
            {
                DistanceReference distanceReference = new DistanceReference();
                distanceReference.ID_FirstPoint = i.WarehouseID;
                distanceReference.NameFirstPoint = i.Name;
                distanceReference.TypeFirstPoint = "Склад";
                distanceReference.ID_SecondPoint = factories.FactoryID;
                distanceReference.NameSecondPoint = factories.Name;
                distanceReference.TypeSecondPoint = "Завод";
                distanceReference.Distance = random.Next(15, 200);
                db.DistanceReferences.Add(distanceReference);
            }
            foreach (Depot i in db.Depots)
            {
                DistanceReference distanceReference = new DistanceReference();
                distanceReference.ID_FirstPoint = factories.FactoryID;
                distanceReference.NameFirstPoint = factories.Name;
                distanceReference.TypeFirstPoint = "Завод";
                distanceReference.ID_SecondPoint = i.DepotID;
                distanceReference.NameSecondPoint = i.Name;
                distanceReference.TypeSecondPoint = "Автобаза";
                distanceReference.Distance = random.Next(15, 200);
                db.DistanceReferences.Add(distanceReference);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Factories");
        }


        //=======================================================
        public ActionResult BackToHome()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("Factories");
        }

        //=======================================================

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Factory factories = await db.Factories.FirstOrDefaultAsync(f => f.FactoryID == id);
                if (factories != null)
                    return View(factories);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Factory factory)
        {
            db.Factories.Update(factory);
            await db.SaveChangesAsync();
            return RedirectToAction("Factories");
        }

        //=======================================================

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Factory factory = await db.Factories.FirstOrDefaultAsync(p => p.FactoryID == id);
                if (factory != null)
                    return View(factory);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Factory factory = await db.Factories.FirstOrDefaultAsync(p => p.FactoryID == id);
                if (factory != null)
                {
                    db.Factories.Remove(factory);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Factories");
                }
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Diplomka/Views/Factory/Create.cshtml
@model Diplomka.Models.Factory

@{
    ViewBag.Title = "Новый завод";
}

<h2>Добавление нового завода</h2>

<form asp-action="Create" asp-controller="Factory">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название завода</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Address" class="control-label">Адрес</label>
        <input type="text" asp-for="Address" class="form-control" />
    </div>      

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-primary" />
    </div>
</form>

<a asp-action="BackToHome" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Factory/Delete.cshtml
@model Diplomka.Models.Factory
@{
    ViewBag.Title = "Удаление данных о заводе";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите удалить данные о заводе №@Model.FactoryID ?</dt>
    </dl>

    <div>
        <form asp-controller="Factory" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Удалить" />
            </div>
        </form>
    </div>
</div>
<a asp-action="BackToHome" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Factory/Edit.cshtml
@model Diplomka.Models.Factory
@{
    ViewBag.Title = "Редактирование данных завода";
}

<h3>Изменение данных завода</h3>

<form asp-action="Edit" asp-controller="Factory" asp-route-id="@Model.FactoryID">
    <div class="form-group">
        <label hidden="true" asp-for="FactoryID" class="control-label">Id завода</label>
        <input type="number" hidden="true" asp-for="FactoryID" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название завода</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Address" class="control-label">Адрес</label>
        <input type="text" asp-for="Address" class="form-control" />
    </div>      

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
</form>

<a asp-action="BackToHome" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Factory/Factories.cshtml
@model IEnumerable<Diplomka.Models.Factory>
@{
    ViewData["Title"] = "Список заказчиков";
}

<!DOCTYPE html>

<html>
<head>
    <title>Заводы</title>
</head>

<body>
    <h2>Заводы</h2>
    @if (Diplomka.Controllers.AccountController.Role=="Администратор")
    {
        <h5><a asp-action="Create"> Новый завод</a></h5>
    }

    <table class="table table-bordered table-primary">
        <tr>
            <th>Id завода</th>
            <th>Название</th>
            <th>Адрес</th>            
            <th></th>
            <th></th>

        </tr>
        @foreach (Factory factory in Model)
        {
            <tr bgcolor = "#FFFFFF">
                <td>@factory.FactoryID</td>
                <td>@factory.Name</td>
                <td>@factory.Address</td>    
                 @if (Diplomka.Controllers.AccountController.Role=="Администратор")
                {
                     <td><a asp-action="Edit" asp-controller="Factory" asp-route-id="@factory.FactoryID">Изменить</a></td> 
                     <td><a asp-action="Delete" asp-controller="Factory" asp-route-id="@factory.FactoryID">Удалить</a></td>       
                }  
                
            </tr>
        }      
    </table>
</body>
</html>