Diplomka/Models/CargoRemnant.cs
namespace Diplomka.Models
{
    public class CargoRemnant  //остатки груза на складе
    {
        public int CargoRemnantID { get; set; }

        public int? WarehouseID { get; set; }
        public Warehouse Warehouse { get; set; }

        public int? GrainID { get; set; }
        public Grain Grain { get; set; }

        public int Volume { get; set; }
    }
}

Diplomka/Models/Warehouse.cs
namespace Diplomka.Models
{
    public class Warehouse  //склады
    {
        public int WarehouseID { get; set; }
        public int Identity { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    }
}

Diplomka/Controllers/WarehouseController.cs
using Diplomka.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Diplomka.Controllers
{
    public class WarehouseController : Controller
    {
        MyBaseContext db;

        public WarehouseController(MyBaseContext context)
        {
            db = context;
        }
        public ActionResult Warehouses()
        {
            IQueryable<Warehouse> warehouses = db.Warehouses;
            return View(warehouses.ToList());
        }

        //=======================================================

        public ActionResult CargoRemnants()
        {
            IQueryable<CargoRemnant> cargoRemnants = db.CargoRemnants.Include(c => c.Warehouse)
                                                                 .Include(c => c.Grain);
            return View(cargoRemnants.ToList());
        }

        //=======================================================

        public IActionResult CreateCargoRemnant()
        {
            ViewBag.Warehouse = new SelectList(db.Warehouses.ToList(), "WarehouseID", "Name");
            ViewBag.Grain = new SelectList(db.Grains.ToList(), "GrainID", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCargoRemnant(CargoRemnant cargoRemnant)
        {
            db.CargoRemnants.Add(cargoRemnant);
            await db.SaveChangesAsync();
            return RedirectToAction("CargoRemnants");
        }

        //=======================================================

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Warehouse warehouse)
        {
            db.Warehouses.Add(warehouse);
            await db.SaveChangesAsync();
            return RedirectToAction("AddWarehouseWays");
        }
        public async Task<IActionResult> AddWarehouseWays()
        {
            Random random = new Random();
            Warehouse warehouse = new Warehouse();
            warehouse = db.Warehouses.OrderByDescending(p => p.WarehouseID).First(p => !String.IsNullOrEmpty(p.WarehouseID.ToString()));
            foreach (Factory i in db.Factories)
            {
                DistanceReference distanceReference = new DistanceReference();
                distanceReference.ID_FirstPoint = warehouse.WarehouseID;
                distanceReference.NameFirstPoint = warehouse.Name;
                distanceReference.TypeFirstPoint = "Склад";
                distanceReference.ID_SecondPoint = i.FactoryID;
                distanceReference.NameSecondPoint = i.Name;
                distanceReference.TypeSecondPoint = "Завод";
                distanceReference.Distance = random.Next(15, 200);
                db.DistanceReferences.Add(distanceReference);
            }
            foreach (Depot i in db.Depots)
            {
                DistanceReference distanceReference = new DistanceReference();
                distanceReference.ID_FirstPoint = i.DepotID;
                distanceReference.NameFirstPoint = i.Name;
                distanceReference.TypeFirstPoint = "Автобаза";
                distanceReference.ID_SecondPoint = warehouse.WarehouseID;
                distanceReference.NameSecondPoint = warehouse.Name;
                distanceReference.TypeSecondPoint = "Склад";
                distanceReference.Distance = random.Next(15, 200);
                db.DistanceReferences.Add(distanceReference);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Warehouses");
        }

            //=======================================================
            public ActionResult BackToHome()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("Warehouses");
        }

        //=======================================================
        public ActionResult BackToCargoRemnants()
        {
            // Переход на главную страницу приложения
            return RedirectToAction("CargoRemnants");
        }

        //=======================================================

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Warehouse warehouses = await db.Warehouses.FirstOrDefaultAsync(w => w.WarehouseID == id);
                if (warehouses != null)
                    return View(warehouses);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Warehouse warehouse)
        {
            db.Warehouses.Update(warehouse);
            await db.SaveChangesAsync();
            return RedirectToAction("Warehouses");
        }

        //=======================================================

        public async Task<IActionResult> EditCargoRemnant(int? id)
        {
            ViewBag.Warehouse = new SelectList(db.Warehouses.ToList(), "WarehouseID", "Name");
            ViewBag.Grain = new SelectList(db.Grains.ToList(), "GrainID", "Name");

            if (id != null)
            {
                CargoRemnant cargoRemnant = await db.CargoRemnants.FirstOrDefaultAsync(c => c.CargoRemnantID == id);
                if (cargoRemnant != null)
                    return View(cargoRemnant);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditCargoRemnant(CargoRemnant cargoRemnant)
        {
            db.CargoRemnants.Update(cargoRemnant);
            await db.SaveChangesAsync();
            return RedirectToAction("CargoRemnants");
        }

        //=======================================================

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Warehouse warehouse = await db.Warehouses.FirstOrDefaultAsync(w => w.WarehouseID == id);
                if (warehouse != null)
                    return View(warehouse);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Warehouse warehouse = await db.Warehouses.FirstOrDefaultAsync(p => p.WarehouseID == id);
                if (warehouse != null)
                {
                    db.Warehouses.Remove(warehouse);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Warehouses");
                }
            }
            return NotFound();
        }

        //=======================================================

        [HttpGet]
        [ActionName("DeleteCargoRemnant")]
        public async Task<IActionResult> ConfirmDeleteCargoRemnant(int? id)
        {
            if (id != null)
            {
                CargoRemnant сargoRemnant = await db.CargoRemnants.FirstOrDefaultAsync(с => с.CargoRemnantID == id);
                if (сargoRemnant != null)
                    return View(сargoRemnant);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCargoRemnant(int? id)
        {
            if (id != null)
            {
                CargoRemnant сargoRemnant = await db.CargoRemnants.FirstOrDefaultAsync(c => c.CargoRemnantID == id);
                if (сargoRemnant != null)
                {
                    db.CargoRemnants.Remove(сargoRemnant);
                    await db.SaveChangesAsync();
                    return RedirectToAction("CargoRemnants");
                }
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Diplomka/Views/Warehouse/CargoRemnants.cshtml
@model IEnumerable<Diplomka.Models.CargoRemnant>
@{
    ViewData["Title"] = "Остатки грузов";
}

<!DOCTYPE html>

<html>
<head>
    <title>Остатки грузов на складах</title>
</head>

<body>
    <h2>Остатки грузов на складах</h2>
    @if (Diplomka.Controllers.AccountController.Role=="Администратор")
    {
        <h5><a asp-action="CreateCargoRemnant"> Добавить остатки</a></h5>
    } 
    <table class="table table-bordered table-primary">
        <tr>
            <th>Название склада</th>
            <th>Вид зерна</th>
            <th>Количество</th>  
            <th></th>                
            <th></th>                

        </tr>
        @foreach (CargoRemnant cargoRemnant in Model)
        {
            <tr bgcolor = "#FFFFFF">
                <td>@cargoRemnant.Warehouse.Name</td>
                <td>@cargoRemnant.Grain.Name</td>
                <td>@cargoRemnant.Volume</td>     
                @if (Diplomka.Controllers.AccountController.Role=="Администратор")
                {
                    <td><a asp-action="EditCargoRemnant" asp-controller="Warehouse" asp-route-id="@cargoRemnant.CargoRemnantID">Изменить</a></td> 
                    <td><a asp-action="DeleteCargoRemnant" asp-controller="Warehouse" asp-route-id="@cargoRemnant.CargoRemnantID">Удалить</a></td> 
                } 
                 
            </tr>
        }      
    </table>
</body>
</html>

Diplomka/Views/Warehouse/Create.cshtml
@model Diplomka.Models.Warehouse

@{
    ViewBag.Title = "Новый склад";
}

<h2>Добавление нового склада</h2>

<form asp-action="Create" asp-controller="Warehouse">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название склада</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Address" class="control-label">Адрес</label>
        <input type="text" asp-for="Address" class="form-control" />
    </div>      

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-primary" />
    </div>
</form>
<a asp-action="BackToHome" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Warehouse/CreateCargoRemnant.cshtml
@model Diplomka.Models.CargoRemnant

@{
    ViewBag.Title = "Остатки грузов";
}

<h2>Добавление остатков груза</h2>

<form asp-action="CreateCargoRemnant" asp-controller="Warehouse">    
    
    <div class="form-group">
        <label asp-for="WarehouseID" class="control-label">Склад</label>
        <select asp-for="WarehouseID" asp-items="ViewBag.Warehouse" class="form-control"></select>
    </div>   
    
    <div class="form-group">
        <label asp-for="GrainID" class="control-label">Вид зерна</label>
        <select asp-for="GrainID" asp-items="ViewBag.Grain" class="form-control"></select>
    </div> 
    
    <div class="form-group">
        <label asp-for="Volume" class="control-label">Объём</label>
        <input type="number" asp-for="Volume" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-primary" />
    </div>

</form>

<a asp-action="BackToCargoRemnants" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Warehouse/Delete.cshtml
@model Diplomka.Models.Warehouse
@{
    ViewBag.Title = "Удаление данных о складе";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите удалить данные о складе №@Model.WarehouseID ?</dt>
    </dl>

    <div>
        <form asp-controller="Warehouse" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Удалить" />
            </div>
        </form>
    </div>
</div>
<a asp-action="BackToHome" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Warehouse/DeleteCargoRemnant.cshtml
@model Diplomka.Models.CargoRemnant
@{
    ViewBag.Title = "Удаление данных об остатках груза";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите удалить данные об остатках груза №@Model.CargoRemnantID ?</dt>
    </dl>

    <div>
        <form asp-controller="Warehouse" asp-action="DeleteCargoRemnant" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Удалить" />
            </div>
        </form>
    </div>
</div>
<a asp-action="BackToCargoRemnants" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Warehouse/Edit.cshtml
@model Diplomka.Models.Warehouse
@{
    ViewBag.Title = "Редактирование данных склада";
}

<h3>Изменение данных склада</h3>

<form asp-action="Edit" asp-controller="Warehouse" asp-route-id="@Model.WarehouseID">
    <div class="form-group">
        <label hidden="true" asp-for="WarehouseID" class="control-label">Id склада</label>
        <input type="number" hidden="true" asp-for="WarehouseID" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название склада</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Address" class="control-label">Адрес</label>
        <input type="text" asp-for="Address" class="form-control" />
    </div>      

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>
</form>

<a asp-action="BackToHome" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Warehouse/EditCargoRemnant.cshtml
@model Diplomka.Models.CargoRemnant
@{
    ViewBag.Title = "Редактирование данных";
}

<h3>Изменение остатков грузов</h3>

<form asp-action="EditCargoRemnant" asp-controller="Warehouse">    
    <div class="form-group">
        <label hidden="true" asp-for="CargoRemnantID" class="control-label">Id зерна</label>
        <input type="number" hidden="true" asp-for="CargoRemnantID" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="WarehouseID" class="control-label">Склад</label>
        <select asp-for="WarehouseID" asp-items="ViewBag.Warehouse" class="form-control"></select>
    </div>   
    
    <div class="form-group">
        <label asp-for="GrainID" class="control-label">Вид зерна</label>
        <select asp-for="GrainID" asp-items="ViewBag.Grain" class="form-control"></select>
    </div> 
    
    <div class="form-group">
        <label asp-for="Volume" class="control-label">Объём</label>
        <input type="number" asp-for="Volume" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-primary" />
    </div>

</form>

<a asp-action="BackToCargoRemnants" class="btn btn-primary"> Отмена</a>

Diplomka/Views/Warehouse/Warehouses.cshtml
@model IEnumerable<Diplomka.Models.Warehouse>
@{
    ViewData["Title"] = "Список складов";
}

<!DOCTYPE html>

<html>
<head>
    <title>Склады</title>
</head>

<body>
    <h2>Склады</h2>
    @if (Diplomka.Controllers.AccountController.Role=="Администратор")
    {
        <h5><a asp-action="Create"> Новый склад  </a><a asp-action="CargoRemnants">   | Остатки грузов</a></h5>
    } 

    <table class="table table-bordered table-primary">
        <tr>
            <th>Id склада</th>
            <th>Название</th>
            <th>Адрес</th>            
            <th></th>
            <th></th>

        </tr>
        @foreach (Warehouse warehouse in Model)
        {
            <tr bgcolor = "#FFFFFF">
                <td>@warehouse.WarehouseID</td>
                <td>@warehouse.Name</td>
                <td>@warehouse.Address</td>         
                @if (Diplomka.Controllers.AccountController.Role=="Администратор")
                {
                    <td><a asp-action="Edit" asp-controller="Warehouse" asp-route-id="@warehouse.WarehouseID">Изменить</a></td> 
                    <td><a asp-action="Delete" asp-controller="Warehouse" asp-route-id="@warehouse.WarehouseID">Удалить</a></td>                    } 
                
            </tr>
        }      
    </table>
</body>
</html>